config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "posts#index"

  resources :users do
    collection do
      post "signup"
      post "login"
      post "invite"
    end
  end

  resources :posts do
    collection do
      # post "post"
      post "create"
      # get "posts/post"
      delete "posts/destroy"
      patch "update"
    end
  end

  resources :groups do
    member do
      delete "group_user_destroy"
    end
  end

end

app/models/group.rb
class Group < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  # validates :group_name, numericality: { only_interger: false }
  # validates :group_name, presence: true
  # validates :group_name, uniqueness: { case_sensitive: :true}
  # validates :group_name, length: { minimum: 1, maximum: 10 }
  # validates :group_name, confirmation: { case_sensitive: true }



end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  belongs_to :group

  mount_uploader :image, ImageUploader


  validates :title, presence: true
  validates :title, length: { in: 1..20 }

  validates :content, presence: true
  validates :content, length: { in: 1..256 }

  validates :group_id, presence: true

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # before_action :authenticate_user!

  def index
    if user_signed_in?
      # 投稿一覧表示
      @posts = Post.all.order("created_at DESC")

      #  投稿フォーム用にインスタンスを用意
      @post = Post.new
      #  投稿フォーム用にインスタンスを用意
      @group = Group.new
      # binding.pry
      #  ユーザーが削除可能なグループリスト
      @del_groups_list = Group.where(admin:current_user.id)

      #  新規グループ作成時、ユーザーの名前の表示
      # @name_list = User.where.not(id:current_user.id)


      #  グループボタンを押してPostの表示範囲を指定
      if params[:group]  == nil

      else
        if params[:group] == "all"

          @user_posts = Post.where(user_id:current_user.id).order("updated_at DESC")

          # render json: @user_posts

          respond_to do |format|
            format.html{redirect_to root_path}
            format.json
          end

        elsif params[:group] != "all"
          group_name = Group.find_by(group_name: params[:group])
          # @group_posts = Post.where(group_id: group_name.id)
            # 1
          # query = "select * from posts join users on posts.user_id = users.id"
          query = "select posts.id,title,content,image,users.name,posts.updated_at,group_id from posts join users on posts.user_id = users.id order by posts.updated_at DESC"
          ggg = Post.find_by_sql(query)
          @group_posts = ggg.select{|a| a.group_id == group_name.id}
          # binding.pry
          respond_to do |format|
            format.html{redirect_to root_path}
            format.json
            # render json: @group_posts
          end
        end
      end
    else
    end
  end


  # indexの記述 + 投稿用の記述
  def create
    if user_signed_in?
      # 投稿一覧表示
      @posts = Post.all.order("created_at DESC")

      #  投稿フォーム用にインスタンスを用意
      @post = Post.new
      #  投稿フォーム用にインスタンスを用意
      @group = Group.new
      # binding.pry
      #  ユーザーが削除可能なグループリスト
      @del_groups_list = Group.where(admin:current_user.id)

      #  新規グループ作成時、ユーザーの名前の表示
      # @name_list = User.where.not(id:current_user.id)

      # createアクション用記述
      # binding.pry
      @post = Post.new(
        title: post_params[:title],
        content: post_params[:content],
        image: post_params[:image],
        group_id: post_params[:group_id],
        user_id: current_user.id
      )
      # @post.save

        if @post.save

          redirect_to root_path, flash:{group_create: "投稿に成功しました"}
        else
          # binding.pry
          render "posts/index"

        end


      #  グループボタンを押してPostの表示範囲を指定
      if params[:group]  == nil

      else
        if params[:group] == "all"

          @user_posts = Post.where(user_id:current_user.id).order("updated_at DESC")
          # binding.pry
          # render json: @user_posts

          respond_to do |format|
            format.html{redirect_to root_path}
            format.json
          end

        elsif params[:group] != "all"
          group_name = Group.find_by(group_name: params[:group])
          # @group_posts = Post.where(group_id: group_name.id)

            # 1
          # query = "select * from posts join users on posts.user_id = users.id"
          query = "select posts.id,title,content,image,users.name,posts.updated_at,group_id from posts join users on posts.user_id = users.id order by posts.updated_at DESC"
          ggg = Post.find_by_sql(query)
          # fff = User.find_by_sql(query)
          @group_posts = ggg.select{|a| a.group_id == group_name.id}

          # binding.pry
          respond_to do |format|
            format.html{redirect_to root_path}
            format.json
          end
          # render json: @group_posts
        end
      end
    else
    end
  end



  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end


  def update
    # @post = Post.new
    post = Post.find(params[:id])
    if params[:remove_image].present?
      post.remove_image!
    end
    if post.user_id == current_user.id
      post.update(post_params)
      redirect_to action: :show
    end
  end


  def destroy
    @post = Post.find_by(id: params[:id])
    if @post.destroy
      redirect_to root_path, status:301, flash:{group_delete: "投稿を削除しました"}
    end
  end


  private


  def post_params
    # binding.pry
    params.require(:post).permit(
      [:title],
      [:content],
      [:image],
      [:group_id],
      [:remove_image]
    )
  end

  # # インデックスにログインフォームを設置するため、必要な値を渡すための記述
  # # UsersControllerにてログイン用のアクションを作ったため、不要に。
  # def resource_name
  #   :user
  # end
  # helper_method :resource_name

  # def resource
  #   @resource ||= User.new
  # end
  # helper_method :resource

  # def devise_mapping
  #   @devise_mapping ||= Devise.mappings[:user]
  # end
  # helper_method :devise_mapping

  # def resource_class
  #   User
  # end
  # helper_method :resource_class



end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_error_messages.html.haml
- if post.errors.any?
  - unless post.valid?
    - if errors = post.errors.full_messages_for(column.to_sym)
      %ul
        - errors.each do |error|
          %li=error

app/views/posts/_footer.html.haml
.footer
  .upper
    .copyright COPYRIGHT &#xA9; MASATO YAMADA ALL RIGHTS RESERVED.

app/views/posts/_header.html.haml
.header_wrap.hide
  .header
    .header_title
      = link_to root_path,data: {"turbolinks":false} do
        %h1 GroupBlog
    .header_groug_name

    -# .hbg
    -#   = check_box "hbg","",class:"hbg_btn",checked:""
    -#   = label "hbg","",class:"hbg_btn"

    .header_nav
      - if user_signed_in?
        .header_nav_upper{class:"#{controller.action_name}"}
          %p.waku.use_name_edit-btn
            = current_user.name
          %p
          |
          = link_to destroy_user_session_path, method: :delete, class: 'logout-btn waku' do
            %p ログアウト
        .header_nav_lower{class:"#{controller.action_name}"}
          %p.waku.header_nav_post 投稿する
          %p.waku.header_nav_group.mk_group_btn グループ作成

      - else
        .header_nav_sign-out
          %p
            ログインしてご利用ください

  - if user_signed_in?
    -# ポップアップにてユーザー名変更
    .user_update-pop_one.hidden
      .user_update-pop
        = form_for "", url: user_path(current_user), method: :patch do |f|
          %p
            name:
          = f.text_field :name, value: "#{current_user.name}", class: "text_field_user_name-edit"
          %p
            profile:
          = f.text_area :profile, value: "#{current_user.profile}", class: "text_field_user_profile-edit"
          = f.submit "変更を保存", id:"user-edit_submit"
        .em_user-edit

app/views/posts/edit.html.haml
= render "posts/header"

.main_wrap
  = form_for @post, method: :patch do |f|
    .edit_content
      .edit_logo
        .edit_logo-after
        %h2
          EDIT
        -# = @post.created_at.strftime("%Y/%m/%d %H:%M")
      .edit_content_upper
        %h3
          = f.text_field :title, value:"#{@post.title}"
        %h4
          = @post.user.name
      .edit_content_lower
        .edit_text
          = f.text_area :content, value:"#{@post.content}"
        // // 画像の編集
        // 元々画像が含まれていなければ → 画像のアップロードフォーム
        - unless @post.image.present?
          .form_post_image_prev
            -# - if @post.image?
            = image_tag "", id: 'post_image-preview'
            = image_tag "times-circle-regular.svg",class:"prev-del hidden"
          .form_post_image
            = f.label :image, class: 'form_post_mask_image' do
              %span
                画像のアップロード
              = fa_icon 'picture-o', class: 'icon'
              = f.file_field :image, class: "hidden image_prev"

            // 元々画像が含まれていれば → 画像の削除ボタン＋アップロードフォーム
        - if @post.image.present?
          //  プレビュー
          .edit_image
            = image_tag @post.image.url, class:"image_prev"
          // 削除
          .form_post_image
            = f.check_box :remove_image, class:"hidden"
            = f.label :remove_image, "この画像を削除する",class:"post-edit_remove-btn"

          // 未実装
          // 元の画像の削除 → 違う画像のアップロード
          //   *理由: 一回のアップデートで削除のみにしか対応していないため新規アップが反映されない
          //   *案: 「削除のみ」と、「削除して別の画像をアップ」を分ける
          -# .post-edit_change-image.hidden
          -#   .form_post_image_prev
          -#     -# - if @post.image?
          -#     = image_tag "", id: 'post_image-preview'
          -#     = image_tag "times-circle-regular.svg",class:"prev-del hidden"
          -#   .form_post_image
          -#     = f.label :image, class: 'form_post_mask_image' do
          -#       %span
          -#         画像のアップロード
          -#       = fa_icon 'picture-o', class: 'icon'
          -#       = f.file_field :image, class: "hidden image_prev"
    - if current_user.id == @post.user_id
      .edit_under_btn
        = f.submit "変更を保存"
        -# = link_to "編集する", edit_post_path, method: :get
        = link_to "戻る", "/posts/#{@post.id}", method: :get

= render "posts/header"

app/views/posts/index.html.haml
= render "posts/header"

-# フラッシュメッセージなど
.flash
  -# %span
  -#   グループを作成しました
  - if flash[:group_create]
    .flash_one
      %span.alert
        = flash[:group_create]

  - if flash[:group_create_error]
    .flash_one
      %span.alert
        = flash[:group_create_error]

  - if flash[:group_delete]
    .flash_one
      %span.alert
        = flash[:group_delete]




-# メインコンテンツ表示ゾーン
.main_wrap

  - if user_signed_in?   # サインインしている場合
    -# 新規投稿フォーム タブ
    .form_post_wrap
      .form_post_tab

    -# 投稿一覧 タブ
    .contents_wrap
      .contents_tab
    -# 投稿一覧 タブ
    .group_tab

    -# .demo1.hidden
    -#   ようこそ１
    -# .demo2.hidden
    -#   ようこそ２

    -# グループ作成 フォーム
    .form_group_wrap
      .form_group_one
        .form_group_two.hidden
          .form_group_three
            %h2
              新規グループ作成
            = form_for @group, url: groups_path, method: :post, class:"group-create" do |f|
              %h3
                グループ名を入力してください
              .group-name_field
                = f.text_field :group_name, autofocus: true, autocomplete: "グループ名を入力",class:"new-group_name", maxlength: 12
              %h3
                ユーザを選択してください
              %p
                グループに登録したユーザの投稿を表示します
              .group-user-sel_field
                = f.collection_check_boxes :user_ids, User.where.not(id: current_user.id), :id, :name, include_hidden: false
              = f.hidden_field :admin, value:current_user.id
              = f.submit "グループ作成", id: "form_group_submit"
            .em_group-create


          -# グループの削除
          .group_edit-delete
            .group_d-area
              %h3
                グループの削除
              %p
                選択したグループを削除します
              .group_edit-delete_btns
                -# - current_user.groups.each do |group|
                - @del_groups_list.each do |group|
                  .group_d-list
                    -# = link_to "#{group.group_name}", "/groups/#{group.id}", method: :delete
                    %div{id:"#{group.id}"}
                      = group.group_name

            -# グループの削除確認用のモーダル
            .group-modal_one.hidden
              .group-modal
                %span
                  このグループを削除してもよろしいですか？
                .group-modal_btns
                  .group-modal_n
                    取り消す
                  .group-modal_d
                    削除する


    -# Blog 新規投稿フォーム フォーム
    .form_post_one
      .form_post_two.hidden
        .form_post_three
          %h2 投稿フォーム
          .form_post
            %h3
              グループの選択
            %p
              投稿するグループを選択してください

            = form_for @post,url:"/posts" do |f|
              .form_post_group-btns
                - current_user.groups.each do |group|
                  = f.radio_button :group_id, :"#{group.id}", class:"form_post_groups-btn"
                  = f.label :"group_id_#{group.id}", "#{group.group_name}"
                = render partial: 'error_messages', locals: {post:@post , column: "group_id"}

              .title-content
                %h3
                  投稿するブログのタイトル
                = f.text_field :title, class: 'form_post_title', placeholder: 'タイトル', maxlength: 15
                = render partial: 'error_messages', locals: {post: @post, column: "title"}
                %h3
                  本文テキスト
                = f.text_area :content, class: 'form_post_content', placeholder: '本文テキスト', maxlength: 255
                = render partial: 'error_messages', locals: {post: @post, column: "content"}

              .form_post_image_prev
                -# - if @post.image?
                = image_tag "", id: 'post_image-preview'
                = image_tag "times-circle-regular.svg",class:"prev-del hidden"
              .form_post_image
                = f.label :image, class: 'form_post_mask_image' do
                  %span
                    画像のアップロード
                  = fa_icon 'picture-o', class: 'icon'
                  = f.file_field :image, class: "hidden image_prev"
                  -# = image_tag "times-circle-regular.svg",class:"prv-del"

                  -# = f.file_field :image, id:"image_prev", class: 'hidden'


                -#   <img id="avatar_img_prev" src="#" class='hidden' />  <!-- 1行追加 -->
                -# <% if current_user.persisted? && current_user.avatar? %>
                -#   <%= image_tag current_user.avatar.to_s, class: 'avatar_present_img' %>    <!-- classを追加 -->
                -#   <label><%= f.check_box :remove_avatar %> 画像を削除</label>
                -# <% else %>
                -#   <%= image_tag 'no_avatar.png', class: 'avatar_present_img' %>   <!-- classを追加 -->
                -#   <%= f.hidden_field :avatar_cache %>
                -# <% end %>
                -# = f.hidden_field :image_cache

              -# = f.file_field :imager, id: 'post_img'

              .form_post_submit-btn
                = f.button '投稿する',type: "submit" , class: 'form_post_submit'



    -# グループ・ボタンエリア
    .groups_wrap
      .groups
        %h3
          グループの投稿を表示
        %p
          選択したグループの投稿を表示します

        = radio_button_tag "groups","all",type:"radio", class:"group_name"
        = label_tag "groups_all", "#{current_user.name}の投稿", class:"group_name",id:"my_all_posts-btn"

        - current_user.groups.each do |group|
          .group-btn_one
            = link_to root_path, class: "hoge", id:"group_#{group.id}" do
              = radio_button_tag "groups","#{group.group_name}",type:"radio", class:"group_name"
              = label_tag "groups_#{group.group_name}", "#{group.group_name}", class:"group_name"

            .group_users.hidden
              = form_for "", url: "groups/update", method: :patch do |f|
                %h3
                  = f.text_field :group_name, value:"#{group.group_name}"
                = f.submit "グループ名の変更を保存", id:"group_name-edit_submit"

                .foot_group_users_title
                  = group.group_name
                  -# グループメンバー
                .group_users_one
                  .modal_gu_one.hidden
                    .modal_gu
                      %span
                        選択したユーザーをグループから削除してもよろしいですか？
                      .modal_gu_btns
                        .modal_gu_n
                          取り消す
                        .modal_gu_d
                          削除する
                  - group.group_users.each do |user|
                    %div{class:"footer_group_user",id: "#{user.id}"}
                      %p{class:"footer_group_user-btn"}
                        = user.user.name
                      -# = link_to "/groups/#{user.id}/group_user_destroy", method: :delete do
                      .user_option.hidden
                        .prof
                          %pre
                            = user.user.profile
                        - if current_user.id == group.admin
                          .del-user
                            = image_tag "times-circle-regular.svg" ,class:"abc"
                            %p
                              このメンバーをグループから外す

                          -# %p{id:"group_add_#{user.user.id}"}
                          -# = user.user.name
                  // 保留中---グループユーザーの追加
                  -# .add_btn
                  -#   +
                  -# .add_user_list.group-user-sel_field
                  -#   -# - group.group_users.each do |user|
                  -#   -#   %p{class:"user_id_#{user.id}"}
                  -#   -#   = user.user.name

                  -#   = f.collection_check_boxes :user_ids, User.where.not(id: group.group_users.user.id), :id, :name, include_hidden: false
                  -# = f.hidden_field :group_id, value:group.id



    -# 投稿一覧 タイル表示
    .contents_one
      .contents_two
        -# = image_tag @image.url
        .contents_three
          -# 以下Ajaxにてcontentを表示



  - else          # サインインしていない場合
    -# サインインフォーム タブ
    .form_signin_wrap
      .form_signin_tab

    -# サインアップフォーム タブ
    .form_signup_wrap
      .form_signup_tab

    .pop-up_lets-signup
      .pop-up_lets-signup_two
        .pop-up_lets-signup_text
          %p
            まずはサインアップしよう！
        .pop-up_lets-signup_arrow
          = fa_icon 'mouse-pointer', class: 'icon'
    .guide_demo-user
      %h3
        デモユーザーを利用してアプリを試す
      %p
        登録をせずにアプリを試すことができます。
      = link_to invite_users_path, method: :post do
        .go-demo
          GO
      -# .demo-btn_maru


    -# サインインフォーム 表示
    .form_signin_one
      .form_signin_two.hidden
        %h2
          ログイン
        -# %p 登録しているユーザーでログイン
        .form_signin
          -# = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
          = form_for "", url:login_users_path do |f|
            .field
              .field-label
                = f.label :メールアドレス
              .field-signin-input_email
                = f.email_field :email, autofocus: true
              .field
                .field-label
                  = f.label :パスワード
                  %br
                  %i (英数字6文字以上)
                .field-signin-input_pass
                  = f.password_field :password, autocomplete: "off", minlength: 6, maxlength: 12
              .sign_btn
                = f.submit "ログイン",id:"signin_submit"
        -# = render "devise/shared/links"
        .em_signin


    -# サインアップフォーム
    .form_signup_one
      .form_signup_two.hidden
        %h2
          新規登録
        .form_signup
          = form_for "",url: signup_users_path, method: :post do |f|
            .field
              .field-label
                = f.label :お名前
                %br/
              .field-signup-input_name
                = f.text_field :name, autofocus: true, autocomplete: "name", maxlength: 12
              .field-label
                = f.label :メールアドレス
                %br
              .field-signup-input_email
                = f.email_field :email, autofocus: true, autocomplete: "email"
              .field-label
                = f.label :パスワード
                %br
                %i (英数字6文字以上)
                - if @minimum_password_length
                  %em
                    (#{@minimum_password_length} characters minimum)
                %br/
              .field-signup-input_pass
                = f.password_field :password, autocomplete: "new-password", minlength: 6, maxlength: 12
              .field
                = f.label :パスワードの再入力
                %br
              .field-signup-input_pass_conf
                -# %i 確認の為、パスワードの再入力
                = f.password_field :password_confirmation, autocomplete: "new-password", minlength: 6, maxlength: 12
              .sign_btn
                = f.submit "新規登録",id:"signup_submit"
              .em_signup
          -# = render "devise/shared/links"

    -# .brank_div





= render "posts/footer"

app/views/posts/show.html.haml
= render "posts/header"

.main_wrap

  .show_content
    .show_date
      %p
        = @post.created_at.strftime("%Y/%m/%d %H:%M")
    .show_content_upper
      %h3
        = @post.title
      %h4
        = @post.user.name
    .show_content_lower
      .show_text
        %p
          = safe_join(@post.content.split("\n"), tag(:br))
      - if @post.image.present?
        .show_image
          -# = link_to "",url:"#{@post.image.url}" do
          = image_tag @post.image.url

  - if current_user.id == @post.user_id
    .show_under_btns
      = link_to "編集する", edit_post_path, method: :get
      = link_to "削除する", "#",class:"show_modal_open"

  .show_under_btns_lower
    = link_to "戻る", root_path, method: :get

  .post-modal_one.hidden
    .post-modal
      %span
        この投稿を削除してもよろしいですか？
      .post-modal_btns
        .post-modal_n
          取り消す
        = link_to "", url:posts_destroy_posts_path, method: :delete do
          .post-modal_d
            削除する
= render "posts/footer"